spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect

    # 프로젝트 시작 시 data.sql 파일 실행
    defer-datasource-initialization: true
  sql:
    init:
      mode: always